### ISSUE TITLE
Help needed 

### ISSUE THREAD

**Issue by ThodorisElissaios** [riderx/capacitor-updater#2]
Hello ! 
Since recent ionic crazy pricing trying to find solution :)

I am new to capacitor only cordova used in the past .

testing on iOS

 `async update() {
    const update = await CapacitorUpdater.updateApp({
      url: 'https://myftpurl/upate.zip',
    });
    console.log(update);
  }`

gives me` {done: false}`

(upate.zip is my www zipped)

**Comment by riderx** [comment]
Hello @ThodorisElissaios thanks for the feedback, the module is not finished yet. I struggle to have the update process function, I watching the code of older tool but still don't understand everything.
I will keep you informed on my progress

**Comment by riderx** [comment]
Hello @ThodorisElissaios  can you give it a try again ?
I made it work for IOS and Android !

**Comment by akashdusky** [comment]
error: not a statement
        String current = pathHot.length() >= 10 ? pathHot.substring(pathHot.length() - 10) : 'default';


there is just this issue android 
                                                                                               ^

**Comment by akashdusky** [comment]
i fixed that and this popped up 
idk if im doing something wrong but it worked flawless on ios 
 return editor.getString("lastPathHot", "");
                     ^
  symbol:   method getString(String,String)
  location: variable editor of type Editor

**Comment by riderx** [comment]
Thanks for the feedback @akashdusky i will do more test in Android, I was focus in ios for the last time maybe I forgot some fix in Android

**Comment by riderx** [comment]
I updated, sorry i did the update in vs code, it didn't show me my simple error

**Comment by riderx** [comment]
I have found other issue in android I'm on it

**Comment by riderx** [comment]
Fixed, @akashdusky can you try ?
