### ISSUE TITLE
Error: "CapacitorUpdater" plugin is not implemented on android

### ISSUE THREAD

**Issue by osmanraifgunes** [riderx/capacitor-updater#4]
core.js:6210 ERROR Error: Uncaught (in promise): Error: "CapacitorUpdater" plugin is not implemented on android
Error: "CapacitorUpdater" plugin is not implemented on android

My function for update is : 

```
  async updateHybrid() {
    var self = this;
    const version = await CapacitorUpdater.download({
      url: 'http://92.168.1.25/downloadhybridversion',
    })
    await CapacitorUpdater.set(version)
  }
```

my versiın is "capacitor-updater": "^1.0.22"

**Comment by osmanraifgunes** [comment]
Adding `add(CapacitorUpdaterPlugin.class);`  to MainActivity of app solved my problem.

**Comment by Al-mudather** [comment]
how did you solve the issue
