### ISSUE TITLE
CapacitorUpdater.list() does not return correclty serialized result

### ISSUE THREAD

**Issue by manu2311** [riderx/capacitor-updater#5]
Hi,

I'm experimenting with your lib, cause I also want to use a simple workflow without AppFlow.
I'm testing with an Android emulator and the latest version of capacitor-updater and having issues with the list() method.
Calling list() from my Angular application and calling JSON.stringify on the result shows that the serialization seems not to work as expected.
```typescript
CapacitorUpdater.list().then(x => console.log(JSON.stringify(x)));
// output: {"versions":"[/data/user/0/de.tcwolfach/files/versions/SmuZ3lRen7, /data/user/0/de.tcwolfach/files/versions/gy1sGvaZ5f, /data/user/0/de.tcwolfach/files/versions/ey6GwoMTy8, /data/user/0/de.tcwolfach/files/versions/nlppoSqiMB]"}
```
As you can see the versions-Property is not a an array of strings. Instead it's a string property.

I'm not a Java expert, but it looks like the resulting string is not a correctly serialized string, it's the result of calling toString() on an ArrayList.
Changing this code in node_modules folder:
```Java
public void list(PluginCall call) {
        ArrayList<String> res = implementation.list();
        JSObject ret = new JSObject();
        ret.put("versions", res);
        call.resolve(ret);
    }
```
to this code
```Java
public void list(PluginCall call) {
        ArrayList<String> res = implementation.list();
        JSObject ret = new JSObject();
        ret.put("versions", new JSArray(res));
        call.resolve(ret);
    }
```

fixed the problem.
I only checked the issue for Android, maybe the same problem occurs in iOS.

**Comment by riderx** [comment]
@manu2311 thanks a lot for the feedback, you are right i forgot to do that in java ! I will check your PR

**Comment by riderx** [comment]
Fix in your PR
