### ISSUE TITLE
Auto-revert on failed install

### ISSUE THREAD

**Issue by lincolnthree** [riderx/capacitor-updater#8]
If the new version of the updated code does not run properly, the system should revert to the previously working version.

Previous plugins that have implemented "code-push updates" provide a feature where developers can specify when an update succeeds. Otherwise the update will be rolled back to the previous working version:

```

onAppStarted() {
      CapacitorUpdater.notifyApplicationReady(); 

      // If ".notifyApplicationReady()" is not called within ~5s (or a configured timeout) of an update & reload,
      // the update should be considered failed and the previous version should be loaded.
}

```

Example/Reference: https://github.com/mapiacompany/capacitor-codepush#codepushnotifyapplicationready

**Comment by riderx** [comment]
Thanks @lincolnthree that a great issue, i will have a look and see if how i can do it .

**Comment by ThodorisElissaios** [comment]
@riderx I think this is critical

**Comment by riderx** [comment]
@lincolnthree @ThodorisElissaios this is done on the latest version.
I added the auto update system, who auto revert a version if notifyAppReady is not called :)
You can see the documentation there : 

https://doc.capgo.app/Capacitor-updater-plugin-31ff89b3bfb1417387dbb57f07cfb5d5#194ea4d2859f4a7da41e9ba89653af2f

**Comment by lincolnthree** [comment]
Huzzah! Awesome work! I'll check it this week, hopefully. Working on a big new update - few things to finish up!
