### ISSUE TITLE
What should be in dist.zip?

### ISSUE THREAD

**Issue by sp-cmingay** [riderx/capacitor-updater#9]
Hi there, thanks for sharing this project, I'm really looking forward to using it! Sorry if the answer to this is already out there and I've just missed it!

I'm just trying to give it a test with Android but I'm just wondering what I should be including in the update zip file?

I am using svelte, so I had assumed I should just zip up the contents of the build folder when running `npm run build`

I am attempting to apply the update as follows, I'm not catching any exceptions but the app doesn't appear to update.

```
const updateNow = async () => {
        try {
            const version = await CapacitorUpdater.download({
                url: 'http://192.168.0.39:45456/api/v1/mockreceiver/build.zip',
            })
            await SplashScreen.show()
            await CapacitorUpdater.set(version)
            await SplashScreen.hide()
        }catch (e){
            console.log(e);
        }

    }
```

Thanks again

Oh also, should I be adding anything to `onCreate()` in MainActivity for this plugin? I'm currently assuming not.

**Comment by riderx** [comment]
@sp-cmingay You seems doing it right !
In your zip file you should have your `dist` folder or the content of it directly.
Means ( all js html css files)
Do you app show the SplashScreen ?
I'm available this week to help you ! join the discord :
https://discord.gg/VnYRvBfgA6

**Comment by lincolnthree** [comment]
^ This should probably be put in the Github docs

**Comment by sp-cmingay** [comment]
Thanks @riderx yup that's right I have the contents of the dist folder (well, the build folder on my machine, but that's still the compiled svelte app.

The splashscreen shows and hides and as mentioned no apparent errors or anything, I'll have a bit more of a play just to check I'm not getting anything wrong my side

**Comment by sp-cmingay** [comment]
OK so I was actually using SvelteKit in my original test, however I've just tried again with a brand new app using Svelte instead and it works as expected! 

I suspect it was actually something to do with how sveltekit does server side rendering and the patch was actually getting applied, it was just being instantly overwritten when reopening the app.

Happy for this to be closed now, but thanks for your quick response
